import type { NavItem, Product } from '@/types'

export const NAV_ITEMS: NavItem[] = [
  { label: 'Sortiment', href: '/sortiment' },
  { label: 'Über uns', href: '/ueber-uns' },
  { label: 'Kontakt', href: '/kontakt' },
]

export const PRODUCTS: Product[] = [
  // Speiseeis hergestellt mit dem Besten der Milch
  {
    id: 'milch-vanille',
    name: 'Vanille',
    category: 'milcheis',
    description: 'Klassische Bourbon-Vanille — cremig, vollmundig und zeitlos. Der Bestseller in jedem Eiscafé.',
    sizes: ['5.600 ml'],
    featured: true,
  },
  {
    id: 'milch-schokolade',
    name: 'Schokolade',
    category: 'milcheis',
    description: 'Dunkle Edelbitter-Schokolade trifft auf cremige Eisbasis aus bester Milch. Intensiv und unwiderstehlich.',
    sizes: ['5.600 ml'],
    featured: true,
  },
  {
    id: 'milch-stracciatella',
    name: 'Stracciatella',
    category: 'milcheis',
    description: 'Zarte Eisbasis aus bester Milch mit feinen Schokoladensplittern — ein Klassiker für jeden Anlass.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-amarena-kirsch',
    name: 'Amarena-Kirsch',
    category: 'milcheis',
    description: 'Cremiges Speiseeis mit echten Amarena-Kirschen aus Italien — fruchtig, aromatisch, unverwechselbar.',
    sizes: ['5.600 ml'],
    featured: true,
  },
  {
    id: 'milch-haselnuss',
    name: 'Haselnuss',
    category: 'milcheis',
    description: 'Geröstete Haselnüsse treffen auf cremiges Speiseeis aus bester Milch. Nussig und ungemein befriedigend.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-cookies',
    name: 'Cookies',
    category: 'milcheis',
    description: 'Knusprige Cookie-Stücke in cremiger Eisbasis — ein Favorit bei Jung und Alt.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-joghurt-natur',
    name: 'Joghurt Natur',
    category: 'milcheis',
    description: 'Frischer Joghurt-Geschmack in cremiger Form — leicht, erfrischend und angenehm mild.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-joghurt-waldbeere',
    name: 'Joghurt Waldbeere',
    category: 'milcheis',
    description: 'Die Frische von Joghurt trifft auf aromatische Waldbeeren. Eine fruchtige Verführung.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-cappuccino',
    name: 'Cappuccino',
    category: 'milcheis',
    description: 'Feines Kaffeearoma in cremigem Speiseeis — für alle, die ihren Espresso auch als Eis genießen.',
    sizes: ['5.600 ml'],
    featured: true,
  },
  {
    id: 'milch-walnuss',
    name: 'Walnuss',
    category: 'milcheis',
    description: 'Knackige Walnüsse verleihen diesem cremigen Speiseeis eine charaktervolle, leicht herbe Note.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-malaga',
    name: 'Malaga',
    category: 'milcheis',
    description: 'Rum-getränkte Rosinen in cremiger Eisbasis — ein Klassiker mit südländischem Charme.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-minze-schoko',
    name: 'Minze-Schoko',
    category: 'milcheis',
    description: 'Kühle Pfefferminze trifft auf dunkle Schokolade — erfrischend und zugleich verführerisch.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-banane',
    name: 'Banane',
    category: 'milcheis',
    description: 'Natürliches Bananenaroma in cremigem Speiseeis aus bester Milch — fruchtig und vollmundig.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-banana-split',
    name: 'Banana-Split',
    category: 'milcheis',
    description: 'Das legendäre Dessert als Speiseeis: Banane, Schokolade und Sahne in einer cremigen Kreation.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-eierpunsch',
    name: 'Eierpunsch',
    category: 'milcheis',
    description: 'Das Winterklassiker-Aroma als cremiges Speiseeis — warm in der Erinnerung, kalt im Glas.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-pistazie',
    name: 'Pistazie',
    category: 'milcheis',
    description: 'Edles Pistazien-Aroma in cremiger Eisbasis aus bester Milch — unverwechselbar und begehrt.',
    sizes: ['5.600 ml'],
    featured: true,
  },
  {
    id: 'milch-coconello',
    name: 'Coconello',
    category: 'milcheis',
    description: 'Zartes Kokos-Aroma trifft auf cremiges Speiseeis — tropisch, mild und unwiderstehlich.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-waldmeister',
    name: 'Waldmeister',
    category: 'milcheis',
    description: 'Das grüne Original mit frischem Waldmeister-Aroma — ein nostalgischer Klassiker neu entdeckt.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-salted-caramel',
    name: 'Salted Caramel mit Crunch',
    category: 'milcheis',
    description: 'Butteriges Karamell mit Meersalz und knusprigem Crunch — die perfekte Balance aus süß und salzig.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-krokant-rum',
    name: 'Krokant mit Rum',
    category: 'milcheis',
    description: 'Knuspriger Mandelkrokant und feine Rum-Note in cremiger Eisbasis — ein Genuss für Erwachsene.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-cassata-siciliana',
    name: 'Cassata Siciliana',
    category: 'milcheis',
    description: 'Das sizilianische Traditionsgebäck als Speiseeis: Ricotta, kandierte Früchte und Pistazien.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-snick-snack',
    name: 'Snick-Snack',
    category: 'milcheis',
    description: 'Karamell, Nougat und knackige Stücke in cremiger Eisbasis — Spaß pur für jede Gastronomie.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-azzuro',
    name: 'Azzuro',
    category: 'milcheis',
    description: 'Frischer Blaubeere-Geschmack in cremigem Speiseeis — lebhaft, fruchtig und verführerisch.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-geroestete-mandel',
    name: 'Geröstete Mandel',
    category: 'milcheis',
    description: 'Aromatisch geröstete Mandeln in cremiger Eisbasis aus bester Milch — nussig und elegant.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'milch-tiramisu',
    name: 'Tiramisù',
    category: 'milcheis',
    description: 'Das Lieblingstiramisu Italiens als cremiges Speiseeis: Mascarpone, Espresso und ein Hauch Amaretto.',
    sizes: ['5.600 ml'],
    featured: true,
  },

  // Fruchteis hergestellt aus Vollfruchtpüree
  {
    id: 'frucht-erdbeere',
    name: 'Erdbeere',
    category: 'fruchteis',
    description: 'Sonnengereiften Erdbeeren in reinem Vollfruchtpüree — intensiv fruchtig und natürlich süß.',
    sizes: ['5.600 ml'],
    featured: true,
  },
  {
    id: 'frucht-zitrone',
    name: 'Zitrone',
    category: 'fruchteis',
    description: 'Erfrischendes Fruchteis aus Vollfruchtpüree — intensiv zitronig, natürlich und lebhaft.',
    sizes: ['5.600 ml'],
    featured: true,
  },
  {
    id: 'frucht-mango',
    name: 'Mango',
    category: 'fruchteis',
    description: 'Reife Mangos als reines Vollfruchtpüree — exotisch, aromatisch und voller Fruchtsüße.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'frucht-aprikose',
    name: 'Aprikose',
    category: 'fruchteis',
    description: 'Goldgelbe Aprikosen aus Vollfruchtpüree — sanft süß, leicht säuerlich und sonnengereift.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'frucht-melone',
    name: 'Melone',
    category: 'fruchteis',
    description: 'Frisches Meloneneis aus reinem Vollfruchtpüree — leicht, erfrischend und sommerlich.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'frucht-himbeere',
    name: 'Himbeere',
    category: 'fruchteis',
    description: 'Vollreife Himbeeren als Vollfruchtpüree — leuchtend rot, fruchtig-säuerlich und aromatisch.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'frucht-waldfrucht',
    name: 'Waldfrucht',
    category: 'fruchteis',
    description: 'Eine Komposition aus Brombeeren, Blaubeeren und Johannisbeeren — natürlich, intensiv und fruchtig.',
    sizes: ['5.600 ml'],
  },
  {
    id: 'frucht-sanddorn',
    name: 'Küsten-Sanddorn',
    category: 'fruchteis',
    description: 'Norddeutscher Sanddorn aus Vollfruchtpüree — einzigartig fruchtig-herb mit regionalem Charakter.',
    sizes: ['5.600 ml'],
    featured: true,
  },
]

export const CATEGORY_LABELS: Record<string, string> = {
  alle: 'Alle',
  milcheis: 'Speiseeis aus bester Milch',
  fruchteis: 'Fruchteis',
  gelato: 'Gelato',
  sonderprodukte: 'Sonderprodukte',
}

export const CATEGORY_SUBTITLES: Record<string, string> = {
  milcheis: 'hergestellt mit dem Besten der Milch',
  fruchteis: 'hergestellt aus Vollfruchtpüree',
}
